version: "3.8"
services:
  data-fi-backend-service:
    image: data-fi-backend-service:latest
    ports:
      - "9202:9202"
    depends_on:
      - data-fi-backend-postgres
      - data-fi-backend-redis
    volumes:
      - ~/logs:/logs
    restart: unless-stopped
  data-fi-backend-postgres:
    image: postgres:16
    volumes:
      - backend-postgres-data:/var/lib/postgresql/data
    env_file: ~/.pg_env
    restart: unless-stopped
    healthcheck:
      test: pg_isready -d data_fi -U data_fi
      interval: 10s
      timeout: 5s
      retries: 5
  data-fi-backend-redis:
    image: redis:7
    restart: unless-stopped
    volumes:
      - backend-redis-data:/data
    command: redis-server --save 60 1
  data-fi-backend-postgres-migration:
    build:
      context: .
      dockerfile: migrate.Dockerfile
    env_file: ~/.pg_env
    depends_on:
      - data-fi-backend-postgres

volumes:
  backend-postgres-data:
  backend-redis-data: